name: Feature Request
description: Suggest a new feature for Veto
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you need.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package should this feature be in?
      options:
        - veto-sdk (TypeScript)
        - veto-sdk (Python)
        - veto-cli
        - All packages
        - New package
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        I'm trying to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: |
        I'd like to be able to...

        Example API:
        ```typescript
        const result = veto.newFeature();
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I've tried...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important for my use case
        - Blocking my adoption of Veto
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
